[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/trainingsplan.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
